### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by roy-shuvashish** [lefakkomies/pynomo-doc#12]
In python 3.7 using Spyder I am getting ''FileNotFoundError: [WinError 2] The system cannot find the file specified''. I am using windows pc.

**Comment by djboulet** [comment]
Impossible to assist without more information.  What exactly are you trying to do?

**Comment by roy-shuvashish** [comment]
I tried to run the example codes from here: https://github.com/lefakkomies/pynomo-doc/tree/master/doc/source/examples
When I run from the shell it shows the following error:  

>  FileNotFoundError: [WinError 2] The system cannot find the file specified
> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\lib\site-packages\pyx\text.py", line 1035, in _cleanup
>     self.do_finish(cleanup=False)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\pyx\text.py", line 1234, in do_finish
>     self.go_typeset()
>   File "C:\ProgramData\Anaconda3\lib\site-packages\pyx\text.py", line 1421, in go_typeset
>     self._execute("\\begin{document}", self.texmessages_begindoc_default + self.texmessages_begindoc, STATE_PREAMBLE, STATE_TYPESET)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\pyx\text.py", line 1091, in _execute
>     self.texoutput.expect("PyXInputMarker:executeid=%i:" % self.executeid)
> AttributeError: 'SingleLatexEngine' object has no attribute 'texoutput'

 
I have installed texlive which is also added into the path. 

Running from the command prompt shows following:
 

> ignoring special 'header=l3backend-dvips.pro'
We are about to extract font information for the Type 1 font 'SFRM1000' from its pfb file. This is bad practice (and it's slow). You should use an afm file instead.
We are about to extract font information for the Type 1 font 'SFRM1000' from its pfb file. This is bad practice (and it's slow). You should use an afm file instead.
We are about to extract font information for the Type 1 font 'SFRM1000' from its pfb file. This is bad practice (and it's slow). You should use an afm file instead.
We are about to extract font information for the Type 1 font 'SFRM1000' from its pfb file. This is bad practice (and it's slow). You should use an afm file instead.
We are about to extract font information for the Type 1 font 'SFRM1000' from its pfb file. This is bad practice (and it's slow). You should use an afm file instead.
We are about to extract font information for the Type 1 font 'SFRM1000' from its pfb file. This is bad practice (and it's slow). You should use an afm file instead.
We are about to extract font information for the Type 1 font 'SFRM1000' from its pfb file. This is bad practice (and it's slow). You should use an afm file instead.
We are about to extract font information for the Type 1 font 'SFRM1000' from its pfb file. This is bad practice (and it's slow). You should use an afm file instead.



For example I ran this code: 
```
from pynomo.nomographer import *
import sys
from pyx import *

sys.path.insert(0, "..")

# allows use of latex commands in PyX such as \frac{a}{b} and \par
pyx.text.set(text.LatexEngine)

N_params_1 = {
    "u_min": 1.1,
    "u_max": 1.6,
    "function": lambda u: u,
    "title": r"$\frac{CAD}{L}$",
    "tick_levels": 4,
    "tick_text_levels": 3,
    "text_format": r"$\$%3.3f$",
    "scale_type": "linear smart",
    "tick_side": "left",
}

N_params_2 = {
    "u_min": 1.0,
    "u_max": 1.5,
    "function": lambda u: u,
    "title": r"$\frac{CAD}{USD}$",
    "tick_levels": 4,
    "tick_text_levels": 3,
    "text_format": r"$%3.4f$",
    "scale_type": "linear smart",
    "title_x_shift": 0.5,
    "title_rotate_text": True,
}

N_params_3 = {
    "u_min": 3.0,
    "u_max": 5.0,
    "function": lambda u: u / 3.78541,
    "title": r"$\frac{USD}{US Gal}$",
    "tick_levels": 4,
    "tick_text_levels": 2,
    "scale_type": "linear smart",
    "text_format": r"$\$%3.3f$",
    "scale_type": "linear smart",
}


block_1_params = {
    "block_type": "type_2",
    "f1_params": N_params_1,
    "f2_params": N_params_2,
    "f3_params": N_params_3,
    "isopleth_values": [[1.3, 1.4, "x"]],
}

main_params = {
    "filename": "ex_gasoline_pricing.pdf",
    "paper_height": 11.0 * 2.54 / 2.0,
    "paper_width": 8.5 * 2.54 / 2.0,
    "block_params": [block_1_params],
    "transformations": [("rotate", 0.01), ("scale paper",)],
    "title_str": r"\huge \textbf{Gas Price Converter}",
    "title_y": 13.50,
    "title_box_width": 15.0,
    "extra_texts": [
        {
            "x": 1.0,
            "y": 12.5,
            "text": r"\noindent Is gasoline cheaper \
                south of the 49\textsuperscript{th}? Use this gas price \
                converter to be sure. In the example \
                shown, \$1.300 $\frac{CAD}{L}$ is the same price as \$3.52 $\frac{USD}{US Gal}$ if the exchange rate is 1.40  $\frac{CAD}{USD}$.",
            "width": 8.0,
        },
        {
            "text": r"\copyright Daniel Boulet (2019-2021)",
            "x": 3.0,
            "y": -0.0,
        },
    ],
    # 'make_grid': True
}
Nomographer(main_params)

```

**Comment by roy-shuvashish** [comment]
The problem is solved. I had fix the path to textlive in my environment variable. Thanks.

**Comment by djboulet** [comment]
Glad to hear problem solved.  Enjoy the nomographs.
